tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "osx-cross/arm"
tap "osx-cross/avr"
brew "xz"
brew "glib"
brew "readline"
brew "circleci"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "exa"
brew "harfbuzz"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-flow"
brew "go"
brew "openjdk@17"
brew "gradle"
brew "librsvg"
brew "grep"
brew "lazygit"
brew "lolcat"
brew "mas"
brew "mkcert"
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "ninja"
brew "node@16"
brew "nss"
brew "octave"
brew "openjdk"
brew "openjdk@11"
brew "openssl@3"
brew "pdsh"
brew "php"
brew "pnpm"
brew "pyvim"
brew "ranger"
brew "redis"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "tree"
brew "wget"
brew "yarn"
brew "zk"
brew "zsh"
cask "aptible"
cask "bartender"
cask "font-fira-code-nerd-font"
cask "google-cloud-sdk"
cask "keycastr"
cask "krisp"
cask "latest"
cask "obsidian"
cask "polypane"
cask "visual-studio-code"
mas "1Password for Safari", id: 1569813296
mas "AtlasVPN", id: 1525872949
mas "Grammarly for Safari", id: 1462114288
mas "HotKey", id: 975890633
mas "MenubarX", id: 1575588022
mas "Spark", id: 1176895641
