tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "ctags"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-flow"
brew "go"
brew "gradle"
brew "grep"
brew "lazygit"
brew "luajit", args: ["HEAD"]
brew "mas"
brew "neofetch"
brew "tree-sitter", args: ["HEAD"]
brew "neovim", args: ["HEAD"]
brew "neovim-remote"
brew "pyvim"
brew "ranger"
brew "ripgrep"
brew "telegram-cli"
brew "tmux"
brew "tree"
brew "wget"
brew "yarn"
brew "zsh"
cask "adoptopenjdk8"
cask "alacritty"
cask "alfred"
cask "amethyst"
cask "bettertouchtool"
cask "brave-browser"
cask "discord"
cask "figma"
cask "firefox"
cask "font-3270-nerd-font"
cask "font-cascadia-mono"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "grammarly"
cask "hyper"
cask "joplin"
cask "keybase"
cask "krisp"
cask "ngrok"
cask "slack"
cask "spotify"
cask "telegram-desktop"
cask "whatsapp"
cask "zoom"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
