export HISTFILE=~/.zsh_history

source "$ZDOTDIR/zsh-functions"
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments

if command -v nvim > /dev/null 2>&1; then
    export EDITOR='nvim'
fi

zsh_add_file "zsh-prompt"
zsh_add_file "zsh-exports"
zsh_add_file "zsh-aliases"

zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "hlissner/zsh-autopair"
zsh_add_plugin "lukechilds/zsh-nvm"
zsh_add_plugin "softmoth/zsh-vim-mode"
zsh_add_completion "esc/conda-zsh-completion"



[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(zoxide init zsh)"

autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

complete -C '/usr/local/bin/aws_completer' aws


