export HISTFILE=~/.zsh_history

source "$ZDOTDIR/zsh-functions"
setopt autocd extendedglob nomatch menucomplete
setopt inc_append_history
setopt interactive_comments

if command -v nvim > /dev/null 2>&1; then
    export EDITOR='nvim'
fi

zsh_add_file "zsh-prompt"
zsh_add_file "zsh-exports"
zsh_add_file "zsh-aliases"

zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "hlissner/zsh-autopair"
zsh_add_plugin "lukechilds/zsh-nvm"
zsh_add_plugin "softmoth/zsh-vim-mode"
zsh_add_completion "esc/conda-zsh-completion"



[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(zoxide init zsh)"

autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

complete -C '/usr/local/bin/aws_completer' aws

source $HOME/.cargo/env

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/estebantrillo/.npm/_cacache/tmp/git-clone-e7b2464b/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/estebantrillo/.npm/_cacache/tmp/git-clone-e7b2464b/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/estebantrillo/.npm/_cacache/tmp/git-clone-e7b2464b/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/estebantrillo/.npm/_cacache/tmp/git-clone-e7b2464b/node_modules/tabtab/.completions/sls.zsh
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/estebantrillo/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/estebantrillo/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/estebantrillo/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/estebantrillo/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
